### ISSUE TITLE
cash received/paid form to vendor/parties to be done.

### ISSUE THREAD

**Issue by manamulya** [awecode/awecounting#13]
there are conditions where i have to pay cash to previously due amounts. I need a form to do so.

**Comment by xtranophilist** [comment]
http://awecounting.com/voucher/cash_receipt/
Cash receipt done.
@roshanshrestha01 Please complete cash payment.

**Comment by manamulya** [comment]
@roshanshrestha01 customer address will be received from party.address
Amount (input x)
current balance( party.balance) is observable ( current balance -x)

**Comment by xtranophilist** [comment]
TODO: current balance- cr/dr, from party api
