### ISSUE TITLE
share/investment/add/  collection data type.

### ISSUE THREAD

**Issue by awemulya** [awecode/awecounting#32]
Collection is simply counting (+ve) Integer value.  ie No of times company have collected investment from shareholders.  Collections crud is not needed. (hide their link temporary can be used for next crud model)

**Comment by manamulya** [comment]
In another way , Investment ( date , lot ) record can have rows of shareholders investment amount
first investment(I1) collected from shareholders ( r1 , r2 , r3 ,....) 
where r is shareholder and his investment amount .

**Comment by manamulya** [comment]
Investment total of all rows is the capital of company.

**Comment by xtranophilist** [comment]
#21
